import React from 'react';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { CeremonyExemptionFilters } from '../components/events/CeremonyExemptionFilters';
import { ClassScheduleEditor } from '../components/academic/ClassScheduleEditor';
import { SchoolNode, UserProfile } from '../types';
const save = vi.hoisted(()=>vi.fn());
vi.mock('../lib/backend',()=>({appData:{setClassSchedule:save}}));
afterEach(()=>{cleanup();vi.resetAllMocks();});
const node:SchoolNode={id:'a',name:'Class A',type:'section',metadata:{classSchedule:{'1':{status:'classes',timeIn:'10:00',timeOut:'17:00'},'5':{status:'no_class'}}}};
const students=[{uid:'alice',name:'Alice',student_id:'123',school_data:{academic_assignment:{terminalGroupId:'a'}}}] as UserProfile[];
const settings={exemptStudentIds:['manual'],allowVolunteerMerit:false,volunteerMeritHours:1,classWindows:{}};
it('previews and applies exemptions per date while preserving manual and prior date selections',()=>{
 const onChange=vi.fn();
 render(<CeremonyExemptionFilters value={{...settings,exemptStudentIdsByDate:{'2026-10-05':['prior']}}} onChange={onChange} roots={[node]} students={students} dates={['2026-10-05','2026-10-09']} editing={false}/>);
 fireEvent.click(screen.getByRole('button',{name:'Filter exempt students by class or schedule'}));
 fireEvent.change(screen.getByLabelText('Exemption filter'),{target:{value:'timeIn'}});
 expect(within(screen.getByLabelText('Exemption preview')).getByText('2026-10-05: 1 matching students in 1 classes')).toBeInTheDocument();
 expect(screen.getByText('2026-10-09: 0 matching students in 0 classes')).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Apply matching exemptions'}));
 expect(onChange).toHaveBeenCalledWith({...settings,exemptStudentIdsByDate:{'2026-10-05':['prior','alice'],'2026-10-09':[]}});
});
it('applies filters to an existing single ceremony and supports removing date exemptions',()=>{
 const onChange=vi.fn();
 const view=render(<CeremonyExemptionFilters value={settings} onChange={onChange} roots={[node]} students={students} dates={['2026-10-09']} editing/>);
 fireEvent.click(screen.getByRole('button',{name:'Filter exempt students by class or schedule'}));
 fireEvent.change(screen.getByLabelText('Exemption filter'),{target:{value:'no_class'}});
 fireEvent.click(screen.getByRole('button',{name:'Apply matching exemptions'}));
 expect(onChange).toHaveBeenCalledWith({...settings,exemptStudentIds:['manual','alice']});
 view.rerender(<CeremonyExemptionFilters value={{...settings,exemptStudentIdsByDate:{'2026-10-09':['alice']}}} onChange={onChange} roots={[node]} students={students} dates={['2026-10-09']} editing={false}/>);
 fireEvent.click(screen.getByRole('button',{name:'Remove exemption alice on 2026-10-09'}));
 expect(onChange).toHaveBeenLastCalledWith({...settings,exemptStudentIdsByDate:{'2026-10-09':[]}});
});
it('saves weekly class schedules, validates end times, and preserves errors for retry',async()=>{
 save.mockRejectedValueOnce({message:'Schedule is outside your scope.'}).mockResolvedValueOnce(undefined);
 const refreshed=vi.fn();
 render(<ClassScheduleEditor node={node} onSaved={refreshed}/>);
 fireEvent.change(screen.getByLabelText('Monday timeOut'),{target:{value:'09:00'}});
 expect(screen.getByRole('button',{name:'Save class schedule'})).toBeDisabled();
 fireEvent.change(screen.getByLabelText('Monday timeOut'),{target:{value:'12:00'}});
 fireEvent.change(screen.getByLabelText('Tuesday class status'),{target:{value:'no_class'}});
 fireEvent.click(screen.getByRole('button',{name:'Save class schedule'}));
 expect(await screen.findByText('Schedule is outside your scope.')).toBeInTheDocument();
 expect(refreshed).not.toHaveBeenCalled();
 fireEvent.click(screen.getByRole('button',{name:'Save class schedule'}));
 expect(await screen.findByText('Class schedule saved.')).toBeInTheDocument();
 expect(save).toHaveBeenLastCalledWith('a',{'1':{status:'classes',timeIn:'10:00',timeOut:'12:00'},'2':{status:'no_class'},'5':{status:'no_class'}});
 expect(refreshed).toHaveBeenCalledTimes(1);
});
